WIP: current deploy code, minus unit tests
ndlib/sfx-deploy-pipeline pull request #1
Opened 2021-02-26 22:40 UTC by jrittenh

2021-04-06 18:51 UTC, ialford requested changes

2021-04-06 18:51 UTC, ialford commented on .github/workflows/ci.yml
> +    branches: [ main ]
```suggestion
    branches-ignore: [ main ]
```

I recommend running on push to each branch, and then again on PR, but not on pushes to `main`. As it is, you won't know that a branch is failing tests until you do the PR, which is potentially wasting time for the committer and reviewer.

2021-04-06 18:51 UTC, ialford commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

NIT: prefer a hardcoded version

2021-04-06 18:51 UTC, ialford commented on README.md
> +Infrastructure code to deploy SFX code to hosted Ex Libris instance
Include an example of how to stand up the stack, including any context overrides that you may do when standing up in test vs production.

2021-04-06 18:51 UTC, ialford commented on src/sfx-deploy-pipeline-stack.ts
> +      additionalInformation: `A new version of https://github.com/ndlib/sfx has been deployed to https://findtext.library.nd.edu/ndu_test and is awaiting your approval. If you approve these changes,
You may want to parameterize the URLs, particularly if you're constructing them somewhere else from the parameter store values - see [DEC Blueprints](https://github.com/ndlib/dec-blueprints/blob/main/src/buzz/buzz-pipeline.ts#L229) as an example

2021-04-08 13:55 UTC, jgondron approved these changes

2021-04-14 12:29 UTC, ialford approved these changes

2021-04-14 14:05 UTC, merged